### PR TITLE
Do not change css class names when building

### PR DESCRIPTION
**Pull request by skjnldsv**
Glad we did some beta lol, it seems module do some weird stuff

| Before | After |
|:---------:|:------:|
|image|image|

Ref https://github.com/nextcloud/server/pull/34868

### CODE REVIEW

**Comment by skjnldsv** [comment]
Bump p lease so we can fix server :grin:

**Review by szaimen — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Mind shedding some light on why esm broke this and how your patch fixes this?

:+1: :elephant:

**Comment by skjnldsv** [comment]
> Mind shedding some light on why esm broke this and how your patch fixes this?

esm is not needed, the `\module:true` is what caused it.
Keep in mind this is a followup to the beta changes and the scss compilation recently added from https://github.com/nextcloud/nextcloud-dialogs/pull/691

#691 was part of the answer on how to properly compile scss with rollup.
This pr is the last missing part

**Comment by ChristophWurst** [comment]
Ok but I still can't follow.

**Comment by skjnldsv** [comment]
> Ok but I still can't follow.

This is about the scss->css compilation, no about the js bundles

**Pull request merged**
