### PR TITLE
Adjust docs for persistent toast

### PR DESCRIPTION
**Pull request by nickvergessen**
See #107

### CODE REVIEW

**Comment by korelstar** [comment]
Sorry, but this doesn't work! Due to https://github.com/nextcloud/nextcloud-dialogs/blob/aab06d3e41fa72dfbcc69ab3a3c2a0cdcef765b2/lib/toast.ts#L77 , `Toastify` is called with option `duration=null` which results in using the default value of 3000 (see https://github.com/apvarun/toastify-js#api).

Therefore, you must use `timeout = -1` for a permanent toast or fix https://github.com/nextcloud/nextcloud-dialogs/blob/aab06d3e41fa72dfbcc69ab3a3c2a0cdcef765b2/lib/toast.ts#L77

**Comment by korelstar** [comment]
@nickvergessen @ChristophWurst  Did you test this?

**Comment by ChristophWurst** [comment]
> @nickvergessen @ChristophWurst Did you test this?

Nope :grin:

**Comment by nickvergessen** [comment]
So I was right in the beginning with #107 which fixed it.
Afterwards I though I'm too stupid

**Comment by ChristophWurst** [comment]
Just that the lib says you should use 0. Let's stick to that.

**Pull request merged**
