### PR TITLE
Fix Dialogs not sticky

### PR DESCRIPTION
**Pull request by jotoeri**
Fixes nextcloud/forms/issues/398

### CODE REVIEW

**Comment by ChristophWurst** [comment]
let me know if you need a release for this

**Comment by jotoeri** [comment]
Yes, would be cool, if there is one before forms-release. So no need to hurry, but i think within the next 3-4 weeks this should be the case...

**Comment by ChristophWurst** [comment]
done :)

**Comment by jotoeri** [comment]
Nice, thank you! :) 👍

**Pull request merged**
